// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBAL88mUOHRoIAPCRMdboEYH2t8p6Qwtg',
    appId: '1:762254696459:web:2ff93dc28d5c443c58670e',
    messagingSenderId: '762254696459',
    projectId: 'comsats-lost-found',
    authDomain: 'comsats-lost-found.firebaseapp.com',
    storageBucket: 'comsats-lost-found.firebasestorage.app',
    measurementId: 'G-7LFM9782KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAcnywwHajesy6IgAfQwzkf3yp6VPyaRI',
    appId: '1:762254696459:android:5e33c01ccbaef5ab58670e',
    messagingSenderId: '762254696459',
    projectId: 'comsats-lost-found',
    storageBucket: 'comsats-lost-found.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBAL88mUOHRoIAPCRMdboEYH2t8p6Qwtg',
    appId: '1:762254696459:web:6ce825913b4ee53c58670e',
    messagingSenderId: '762254696459',
    projectId: 'comsats-lost-found',
    authDomain: 'comsats-lost-found.firebaseapp.com',
    storageBucket: 'comsats-lost-found.firebasestorage.app',
    measurementId: 'G-8XJKWY1W29',
  );
}
